{
  shop {
    name
    description
    products(first: 20) {
      edges {
        node {
          id
          title
          productType
          handle
          variants(first: 250) {
            edges {
              node {
                id
                title
                image {
                  originalSrc
                }
                price
              }
            }
          }
          images(first: 250) {
            edges {
              node {
                originalSrc
              }
            }
          }
        }
      }
    }
  }
}
