query productById($id: ID!) {
  node(id: $id) {
    id
    ... on Product {
      title
      handle
      description
      productType
      variants(first: 250) {
        edges {
          node {
            price
          }
        }
      }
      images(first: 250) {
        edges {
          node {
            originalSrc
          }
        }
      }
    }
  }
}
