{
  shop {
    productByHandle(handle: "activated-dermal-corrective-tonic") {
      id
      title
      handle
      productType
      description
      variants(first: 250) {
        edges {
          node {
            price
          }
        }
      }
    }
  }
}
