query productByHandle($handle: String!) {
  shop {
    productByHandle(handle: $handle) {
      id
      title
      handle
      productType
      description
      variants(first: 250) {
        edges {
          node {
            id
            price
          }
        }
      }
    }
  }
}
